#!/usr/bin/env ruby
require 'json'

token = `cat $HOME/.jiracreds`.strip

if token.empty?
  puts 'Please put your username and password into ~/.jiracreds as <username>:<password> '
  exit
end

unless (story_id = ARGV[0])
  print 'What is the story id or URL? '
  story_id = gets.chomp
end

story_id = story_id.split('/').last

response = `curl --silent -u #{token} -X GET -H "Content-Type: application/json" https://jira.weedmaps.systems/rest/api/2/issue/#{story_id}`

story = JSON.parse(response)
if story['errorMessages'] || !story['fields']
  puts "Error getting JIRA data #{story}"
else
  # story_name = story['fields']['summary'].chomp.downcase.gsub(/[\s\.]+/, '-').gsub(/[^\w-]/, '')
  story_type = story['fields']['issuetype']['name'].downcase.gsub(/[\s\.]+/, '-').gsub(/[^\w-]/, '')
  name = "#{story_type}/#{story_id}"
  puts name

  # Optionally you can uncomment out this line to have the script automatically
  # create and push the branch to origin. If you do that then just run the script
  # without using git like shown below.

  `git push origin HEAD:refs/heads/#{name} && git fetch origin && git branch --track #{name} origin/#{name} && cd . && git checkout #{name}`
end